application: gcdc2013-jiga
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /gplus
  script: gplus.php   
  
- url: /youtube
  script: youtube.php 
  
- url: /utsearch
  script: utsearch.php
  
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /google
  static_dir: google
  
  
- url: .*
  script: main.php
  
 

  
  
